name: glofrim3

channels:
  - conda-forge
  - defaults

dependencies:
  - configparser
  - click>=7.0
  - netcdf4>=1.4.2
  - numpy
  - pcraster
  - pip>=20.0
  - python>=3.6
  - python-dateutil>=2.8
  - pytz>=2019.3
  - rasterio==1.1
  - rtree>=0.9.3
  - six>=1.14
  - wflow
  - pip:
    - bmi-python>=0.2.6
